fix: remove console error (#10)
This is to avoid the following error showing up every time running a
test e.g. from VSCode or WebStorm instead of the CLI via NX:

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at NxGroupRunner.runTests ...